version: "3.8"
services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  silo1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "30000:30000"
    environment:
      - Orleans:GatewayPort=30000
      - Redis:ConnectionString=redis:6379
    depends_on:
      - redis

  silo2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
      - "30001:30001"
    environment:
      - Orleans:GatewayPort=30001
      - Redis:ConnectionString=redis:6379
    depends_on:
      - redis

  silo3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
      - "30002:30002"
    environment:
      - Orleans:GatewayPort=30002
      - Redis:ConnectionString=redis:6379
    depends_on:
      - redis
