version: "3.8"
services:

  redis:
    image: redis:7.0
    ports:
      - "6379:6379"

  silo1:
    build: .
    ports:
      - "8080:8080"
      - "30000:30000"
    environment:
      - Redis:ConnectionString=redis:6379
    depends_on:
      - redis

  silo2:
    build: .
    ports:
      - "8081:8080"
      - "30001:30000"
    environment:
      - Redis:ConnectionString=redis:6379
    depends_on:
      - redis

  silo3:
    build: .
    ports:
      - "8082:8080"
      - "30002:30000"
    environment:
      - Redis:ConnectionString=redis:6379
    depends_on:
      - redis
